[mypy]

# Versión de Python usada para el análisis
python_version = 3.10.12

# Revisa funciones sin tipos
check_untyped_defs = True

# Obliga a tipar todas las funciones
disallow_untyped_defs = True

# Ignora librerías sin stubs de tipos
ignore_missing_imports = True

# Fuerza manejo explícito de None
strict_optional = True

# Advierte ignores innecesarios
warn_unused_ignores = True