[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ratio-chartarum"
version = "0.1.0"
description = "Juego de cartas en el terminal"
authors = [{ name = "Carlos Núñez" }]
requires-python = ">=3.10.12,<4.0"
dependencies = ["textual>=0.27"]

[project.scripts]
ratio-chartarum = "main:main"

[project.optional-dependencies]
dev = ["ruff>=0.3", "mypy>=1.5", "pytest>= 7.0"]
